using System;
using System.Collections.Generic;

// Shared prices per displayed unit, measured in half-points.
// Permanent mechanism awards retain their own scarcity price.
internal static class SharedStatCatalog
{
    internal const int AcademyExtraCastHalfPoints=240;
    private static readonly Dictionary<string,int> costs=new Dictionary<string,int> {
        {"Luck",24},{"DashAttackDamage",5},{"FinalWeaponDamage",8},
        {"TeamDefense",16},{"TeamDamage",16},{"TeamElement",48},{"TeamCritical",24},
        {"PhysicalDamage",16},
        {"WeaponRange",4},
        {"BasicAttackDamage",5},
        {"SpecialAttackDamage",5},
        {"MaxHP",4},
        {"MaxMP",4},
        {"Defense",8},
        {"AttackSpeed",6},
        {"MoveSpeed",10},
        {"Critical",12},
        {"MPRegen",8},
        {"MagicCritical",8},
        {"MagicCriticalDamageRate",3},
        {"MagicDamageBonus",5},
        {"MagicCostReduce",8},
        {"FollowerAttackSpeed",5},
        {"FollowerCritical",8},
        {"MPRegenMultiple",8},
        {"FinalMP",6},
        {"FlameSwordIgnoreDefense",10},
        {"HighestElementalDamage",24},
        {"FireDamage",12},
        {"IceDamage",12},
        {"LightningDamage",12},
        {"CooldownRecoverySpeed",6},
        {"DashRecoverySpeed",4},
        {"CriticalDamageRate",4},
        {"HPSteal",0},
        {"FinalDamage",8},
        {"FinalHP",4},
        {"Evasion",10},
        {"TrueDamage",20},
        {"FlameSwordDamage",4},
        {"FrostRelicDamage",5},
        {"DarkCloudDamage",4},
        {"BurnDamage",4},
        {"FreezeDamage",4},
        {"FrostbiteDamage",4},{"FreezeThreshold",200},
        {"ElectricDamage",4},
        {"FollowerDamage",4},
        {"FlameSwordCritical",8},
        {"FlameSwordFastFall",3},
        {"DarkCloudSpeed",2},
        {"BurnSpeed",4},
        {"ChargingCharmBonus",5},
        {"DarkCloudRestoreDuringBattle",2},
        {"MinDarkCloud",32},
        {"BurnDuration",2},
        {"DebuffDamage",6},
        {"DebuffDuration",2},
        {"FollowerDefense",3},
        {"LeafDrop",2},
        {"Negotiation",12},
        {"ChargingCharmAmplify",80},
        {"BurnStack",72},
        {"ElectricStack",72},
        {"DashCount",80},
        {"FlameSwordMax",72},
        {"EXPDrop",4},
        {"PlanetAttackSpeed",4},
        {"PlanetDamage",4},
        {"MPSkillDamage",6},
    };
    internal static int RewardCost(string type) { return costs[type]; }
    internal sealed class Definition {
        internal readonly string Type;internal readonly int RawUnit,EquipmentCost;
        internal Definition(string type,int unit,int equipmentOverride=0) { Type=type;RawUnit=unit;EquipmentCost=equipmentOverride>0?equipmentOverride:RewardCost(type); }
    }
    private static readonly Dictionary<string,Definition> equipment=new Dictionary<string,Definition> {
        {"LUCK",new Definition("Luck",1)},
        {"DASH_ATTACK_DAMAGE",new Definition("DashAttackDamage",1)},
        {"DASH_COUNT",new Definition("DashCount",1,200)},
        {"FINAL_WEAPONDAMAGE",new Definition("FinalWeaponDamage",1)},
        {"ALL_PLAYER_DEFENSE",new Definition("TeamDefense",1)},
        {"ALL_PLAYER_ALL_DAMAGE",new Definition("TeamDamage",1)},
        {"ALL_PLAYER_ELEMENTAL_DAMAGE",new Definition("TeamElement",1)},
        {"ALL_PLAYER_CRIT",new Definition("TeamCritical",1)},
        {"PHYSICAL_DAMAGE",new Definition("PhysicalDamage",1)},
        {"SPECIAL_ATTACK_DAMAGE",new Definition("SpecialAttackDamage",1)},
        {"BASIC_ATTACK_DAMAGE",new Definition("BasicAttackDamage",1)},
        {"CRITICAL_DAMAGE_RATE",new Definition("CriticalDamageRate",1)},
        {"HIGHEST_ELEMENTAL_DAMAGE",new Definition("HighestElementalDamage",1)},
        {"MOVE_SPEED",new Definition("MoveSpeed",1)},
        {"CRITICAL",new Definition("Critical",100)},
        {"ATTACK_SPEED",new Definition("AttackSpeed",1)},
        {"DASH_RECOVERY_SPEED",new Definition("DashRecoverySpeed",1)},
        {"EVASION",new Definition("Evasion",100)},
        {"DEFENSE",new Definition("Defense",1)},
        {"MAX_HP",new Definition("MaxHP",1)},
        {"COOLDOWN_RECOVERY_SPEED",new Definition("CooldownRecoverySpeed",1)},
        {"MP_REGEN",new Definition("MPRegen",1)},
        {"MAGIC_CRITICAL",new Definition("MagicCritical",100)},
        {"MAGIC_CRITICAL_DAMAGE_RATE",new Definition("MagicCriticalDamageRate",1)},
        {"MAX_MP",new Definition("MaxMP",1)},
        {"MP_REGEN_MULTIPLE",new Definition("MPRegenMultiple",1)},
        {"MP_SKILL_DAMAGE",new Definition("MPSkillDamage",1)},
        {"FLAME_SWORD_DAMAGE",new Definition("FlameSwordDamage",1)},
        {"FIRE_DAMAGE",new Definition("FireDamage",1)},
        {"FLAME_SWORD_FAST_FALL",new Definition("FlameSwordFastFall",1)},
        {"FLAME_SWORD_CRITICAL",new Definition("FlameSwordCritical",1)},
        {"FROST_RELIC_DAMAGE",new Definition("FrostRelicDamage",1)},
        {"ICE_DAMAGE",new Definition("IceDamage",1)},
        {"CHARGING_CHARM_BONUS",new Definition("ChargingCharmBonus",1)},
        {"CHARGING_CHARM_AMPLIFY",new Definition("ChargingCharmAmplify",1,200)},
        {"DARK_CLOUD_DAMAGE",new Definition("DarkCloudDamage",1)},
        {"DARK_CLOUD_SPEED",new Definition("DarkCloudSpeed",1)},
        {"DARK_CLOUD_RESTORE_DURING_BATTLE",new Definition("DarkCloudRestoreDuringBattle",1)},
        {"MIN_DARK_CLOUD",new Definition("MinDarkCloud",1)},
        {"BURN_DAMAGE",new Definition("BurnDamage",1)},
        {"BURN_SPEED",new Definition("BurnSpeed",1)},
        {"BURN_STACK",new Definition("BurnStack",1,180)},
        {"FREEZE_DAMAGE",new Definition("FreezeDamage",1)},
        {"FROSTBITE_DAMAGE",new Definition("FrostbiteDamage",1)},
        {"FREEZE_THRESHOLD",new Definition("FreezeThreshold",1)},
        {"ELECTRIC_DAMAGE",new Definition("ElectricDamage",1)},
        {"LIGHTNING_DAMAGE",new Definition("LightningDamage",1)},
        {"ELECTRIC_STACK",new Definition("ElectricStack",1,180)},
        {"DEBUFF_DAMAGE",new Definition("DebuffDamage",1)},
        {"DEBUFF_DURATION",new Definition("DebuffDuration",1)},
        {"FOLLOWER_DAMAGE",new Definition("FollowerDamage",1)},
        {"FOLLOWER_DEFENSE",new Definition("FollowerDefense",1)},
        // Scalar stats share reward prices; only explicit mechanism awards have equipment prices.
        {"LEAF_DROP",new Definition("LeafDrop",1)},
        {"NEGOTIATION",new Definition("Negotiation",1)},
        {"FOLLOWER_ATTACK_SPEED",new Definition("FollowerAttackSpeed",1)},
        {"HP_STEAL",new Definition("HPSteal",1,120)},
        {"TRUE_DAMAGE",new Definition("TrueDamage",1)},
        {"FINAL_DAMAGE",new Definition("FinalDamage",1)},
        {"EXP_DROP",new Definition("EXPDrop",1)},
        {"PLANET_ATTACK_SPEED",new Definition("PlanetAttackSpeed",1)},
        {"PLANET_DAMAGE",new Definition("PlanetDamage",1)},
    };
    internal static Definition Equipment(string statusID) { return equipment[statusID]; }
}
